#!/bin/bash
for (( i = 1; i<=99; i++))
do
        if  [ $((i%2)) -ne 0 ];
  then
    echo $i
  fi
done





for(( i=1; i<=100; i++ ))
  do
    # see if it is odd or even number
    test=$(( $i % 2 ))
    if [ $test -ne 0 ]; 
    then
      echo $i
    fi   
  done
  
  
  
  
  
for i in {1..99..2}
do
echo "$i"
done



seq 1 2 100


for (( i = 1; i<=99; i++))
do
        if  [ "$((i%2))" != 0 ];
  then
    echo $i
  fi
done
